import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/components/Footer/Footer'
import NavbarContainer from '@/components/Navbar/NavbarContainer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="w-screen   bg-gray-50 py-[20px]">
        {/* <NavbarContainer /> */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
